//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Route
    {
        public int Id { get; set; }
        public int Route_No { get; set; }
        public int Payment { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    
        public virtual Payment Payment1 { get; set; }
        public virtual Payment Payment2 { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Routes Routes1 { get; set; }
    }
}
