//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route_Stop
    {
        public int Stop { get; set; }
        public int Route_No { get; set; }
        public System.TimeSpan Travel_time { get; set; }
        public Nullable<int> Previous_Route { get; set; }
        public Nullable<int> Previous_Stop { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Routes Routes1 { get; set; }
        public virtual Stopps Stopps { get; set; }
        public virtual Stopps Stopps1 { get; set; }
    }
}
