//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Scheldue
    {
        public int Id { get; set; }
        public int Route_No { get; set; }
        public string Transport { get; set; }
        public Nullable<int> Additional_Staff { get; set; }
        public int Driver { get; set; }
        public System.DateTime Start_Time { get; set; }
    
        public virtual Additional_Staff Additional_Staff1 { get; set; }
        public virtual Additional_Staff Additional_Staff2 { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Drivers Drivers1 { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Routes Routes1 { get; set; }
        public virtual Routes Routes2 { get; set; }
        public virtual Routes Routes3 { get; set; }
        public virtual Transport Transport1 { get; set; }
        public virtual Transport Transport2 { get; set; }
    }
}
